### PR TITLE
Fix indexerror in para split v3

### PR DESCRIPTION
**Pull request by hyastar**
嗯 已经整改

### CODE REVIEW

**Comment by hyastar** [comment]
I have read the CLA Document and I hereby sign the CLA
recheck

**Comment by hyastar** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hyastar** [comment]
recheck

**Comment by myhloli** [comment]
感觉还是不对，git add的时候只添加para_split_v3.py可以吗，或者在新的目录checkout dev分支，在只修改para_split_v3.py的前提下提交pr到dev分支

**Comment by hyastar** [comment]
抱歉

**Pull request closed without merging**
