### PR TITLE
[chore] udpate DockerFile to fix build bugs

### PR DESCRIPTION
**Pull request by ProseGuys**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation
Modify the dockerfile file to fix the image packaging failure problem caused by the python virtual environment

## Modification
Fix the above problems and optimize the packaging process

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [x] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by ProseGuys** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by drunkpig** [comment]
@ProseGuys please commit code to dev branch.

**Comment by ProseGuys** [comment]
> I have read the CLA Document and I hereby sign the CLA

ok

**Comment by ProseGuys** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ProseGuys** [comment]
> @ProseGuys please commit code to dev branch.

ok

**Comment by ProseGuys** [comment]
> Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://github.com/opendatalab/MinerU/blob/master/MinerU_CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> **2** out of **3** committers have signed the CLA.✅ (kimi360)[https://github.com/kimi360]✅ (ProseGuys)[https://github.com/ProseGuys]❌ @CiaranYoungYou can retrigger this bot by commenting **recheck** in this Pull Request. Posted by the **CLA Assistant Lite bot**.

@drunkpig These two committers did not participate in this PR, this process should not fail

**Pull request closed without merging**
